apiVersion: v1
kind: Service
metadata:
    name: "mykubecluster-7fd5"
    labels:
        app: "mykubecluster-7fd5"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "mykubecluster-7fd5"